spring.application.name=analyzer

# ── PostgreSQL / PostGIS ─────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=senha123

# ── JPA / Hibernate ──────────────────────────────────────
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── IA / Openai ──────────────────────────────────────
spring.ai.openai.api-key=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