name: dnit-ortho-check

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx/tiles:/usr/share/nginx/html/tiles:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data:/usr/share/nginx/data:ro
    restart: unless-stopped
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
  python-api:
    build:
      context: ../python
    ports:
      - "1320:8000"
    volumes:
      - ./nginx/data:/data
    depends_on:
      - db
    env_file:
      - .env
  experimento-avanco:
    build:
      context: ../python/experimentos
    volumes:
      - ./nginx/data:/data:ro
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-02:
    build:
      context: ../python/experimentos
    command: ["python", "comparar_avanco_02.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-03:
    build:
      context: ../python/experimentos
    command: ["python", "experimento_03.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-04:
    build:
      context: ../python/experimentos
    command: ["python", "experimento_04.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento

volumes:
  postgres_data: