name: dnit-ortho-check

services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
  python-api:
    build:
      context: ../python
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    depends_on:
      - db

  

volumes:
  postgres_data: