name: dnit-ortho-check

services:
  experimento-avanco:
    build:
      context: ../python/experimentos
    volumes:
      - ./nginx/data:/data:ro
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-02:
    build:
      context: ../python/experimentos
    command: ["python", "comparar_avanco_02.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-03:
    build:
      context: ../python/experimentos
    command: ["python", "experimento_03.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-04:
    build:
      context: ../python/experimentos
    command: ["python", "experimento_04.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento
  experimento-avanco-05:
    build:
      context: ../python/experimentos
    command: ["python", "experimento_05.py"]
    volumes:
      - ./nginx/data:/data
    env_file:
      - .env
    profiles:
      - experimento

volumes:
  postgres_data: